### ISSUE TITLE
Create a registration form

### ISSUE THREAD

**Issue by hongtuyet91** [chingu-voyages/v52-tier2-team-25#27]
The registration form requires residents to fill in the information:
- Name
- Email
- Phone 
- Address: the user can either type their own address manually, or implement an autocomplete functionality
- Preferred timeslot (more details in another task)

**Comment by hongtuyet91** [comment]
user story #26

**Comment by tigeryash** [comment]
Created a registration page with field validation and is multistep. The user can create an account to solarite and their information is saved into the supabase back end.
